# Generated by Django 4.2.28 on 2026-02-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_customer_alter_booking_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
