# Generated by Django 4.2.28 on 2026-02-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_workeravailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=700.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='worker',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
