# Generated by Django 4.2.28 on 2026-02-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_worker_price_per_hour_worker_total_earnings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
